#!/usr/bin/env bash

# Install brew if it isn't already installed
if test ! $(which brew); then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# Update Homebrew
brew update

# Upgrade existing packages
brew upgrade

# Tap Homebrew bundle
brew tap homebrew/bundle

# Ensure we're in home directory
cd ~

# Run brew bundle
brew bundle
