#!/usr/bin/env bash

# Install brew if it isn't already installed
if test ! $(which brew); then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# Update Homebrew
brew update

# Upgrade existing packages
brew upgrade

# Tap Homebrew bundle
brew tap homebrew/bundle

# Run brew bundle
brew bundle --file ~/Brewfile

# Install vim-plug
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
