#!/bin/bash

# colors
black="\e[1;30m"
blue="\e[1;34m"
cyan="\e[1;36m"
green="\e[1;32m"
orange="\e[1;33m"
purple="\e[1;35m"
red="\e[1;31m"
white="\e[1;37m"
yellow="\e[1;33m"
reset="\e[0m"

mem=$(free -m | awk '/Mem/{printf("%i (free: %i)", $2, $4)}')
swap=$(free -m | awk '/Swap/{printf("%i (free: %i)", $2, $4)}')

printf "${green}Hostname:${reset}   $(uname --nodename)\n"
printf "${green}Mem:\t   ${reset} ${mem}\n"
printf "${green}Swap:\t    ${reset}${swap}\n"
